# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_of_birth', models.DateTimeField(default='1900-01-22 12:45:00.000000')),
                ('gender', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE')], default='F', max_length=1)),
                ('height', models.IntegerField(default=170)),
                ('weight', models.IntegerField(default=60)),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('secure_quest', models.CharField(max_length=200)),
                ('secure_answer', models.CharField(max_length=200)),
            ],
        ),
    ]
