# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitternow', '0002_auto_20161210_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='secure_quest',
            field=models.CharField(max_length=20),
        ),
    ]
