# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitternow', '0003_auto_20161211_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='secure_quest',
            field=models.CharField(max_length=200),
        ),
    ]
