# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitternow', '0005_auto_20161211_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
