# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitternow', '0006_auto_20161211_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default='1900-01-22'),
        ),
    ]
