# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitternow', '0007_auto_20161211_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200)),
                ('calories', models.FloatField(default=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivities',
            fields=[
                ('user_act_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField(default=1)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitternow.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
