# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitternow', '0009_auto_20161212_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivities',
            name='calories_burned',
            field=models.FloatField(default=100),
        ),
    ]
