# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitternow', '0010_useractivities_calories_burned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivities',
            name='activity',
        ),
        migrations.AddField(
            model_name='useractivities',
            name='activity_name',
            field=models.CharField(default='Backpacking, Hiking with pack', max_length=200),
            preserve_default=False,
        ),
    ]
