# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('fitternow', '0011_auto_20161213_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsumption',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('nbdno', models.CharField(max_length=200)),
                ('food_name', models.CharField(max_length=200)),
                ('food_calories', models.FloatField(default=90)),
            ],
        ),
    ]
